# Generated by Django 4.2.4 on 2024-03-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('reson', models.CharField(choices=[('For my team', 'For my team'), ('other', 'other'), ('For my client', 'For my client')], max_length=100)),
                ('mssg', models.TextField()),
            ],
        ),
    ]
