# Generated by Django 4.2.4 on 2024-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='reson',
        ),
        migrations.AddField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('other', 'other'), ('For my team', 'For my team'), ('For my client', 'For my client')], default='null', max_length=100),
        ),
    ]
